%LaunchTime = datetime(2021,03,01,08,00,00);
LaunchTime = datetime(2021,02,11,23,59,00);
%{Task Name, time before endin minutes, team responsible}
Tasks = {{{'Begin Fill on Balloon 1'},{110},{'Red'}},...
         {{'End Fill on Balloon 1'},{95},{'Red'}},...
         {{'Transfer Balloon 1 to Blue Team'},{90},{'Red'}},...
         {{'Begin Fill on Balloon 2'},{85},{'Red'}},...
         {{'End Fill on Balloon 2'},{70},{'Red'}},...
         {{'Transfer Balloon 2 to Blue Team'},{65},{'Red'}},...
         {{'Begin Fill on Balloon 3'},{60},{'Red'}},...
         {{'End Fill on Balloon 3'},{45},{'Red'}},...
         {{'Transfer Balloon 3 to Blue Team'},{40},{'Red'}},...
         {{'Begin Fill on Balloon 4'},{35},{'Red'}},...
         {{'End Fill on Balloon 4'},{20},{'Red'}},...
         {{'Transfer Balloon 4 to Blue Team'},{15},{'Red'}},...
         {{'Begin Preparing Line 1'},{105},{'Green'}},...
         {{'End Preparing Line 1'},{95},{'Green'}},...
         {{'Turn On RDP 1'},{90},{'Green'}},...
         {{'Start EFM 1 Spinning'},{87},{'Green'}},...
         {{'Hand Line 1 to Blue Team'},{85},{'Green'}},...
         {{'Begin Preparing Line 2'},{80},{'Green'}},...
         {{'End Preparing Line 2'},{70},{'Green'}},...
         {{'Turn On RDP 2'},{65},{'Green'}},...
         {{'Start EFM 2 Spinning'},{62},{'Green'}},...
         {{'Hand Line 2 to Blue Team'},{60},{'Green'}},...
         {{'Begin Preparing Line 3'},{55},{'Green'}},...
         {{'End Preparing Line 3'},{45},{'Green'}},...
         {{'Turn On RDP 3'},{40},{'Green'}},...
         {{'Start EFM 3 Spinning'},{37},{'Green'}},...
         {{'Hand Line 3 to Blue Team'},{35},{'Green'}},...
         {{'Begin Preparing Line 4'},{30},{'Green'}},...
         {{'End Preparing Line 4'},{20},{'Green'}},...
         {{'Turn On RDP 4'},{15},{'Green'}},...
         {{'Start EFM 4 Spinning'},{12},{'Green'}},...
         {{'Hand Line 4 to Blue Team'},{10},{'Green'}},...
         {{'Receive Balloon 1 from Red Team'},{90},{'Blue'}},...
         {{'Receive Line 1 from Green Team'},{85},{'Blue'}},...
         {{'Balloon 1 Attached to Line 1'},{80},{'Blue'}},...
         {{'Launch Balloon 1'},{45},{'Blue'}},...
         {{'Receive Balloon 2 from Red Team'},{65},{'Blue'}},...
         {{'Receive Line 2 from Green Team'},{60},{'Blue'}},...
         {{'Balloon 2 Attached to Line 2'},{55},{'Blue'}},...
         {{'Launch Balloon 2'},{30},{'Blue'}},...
         {{'Receive Balloon 3 from Red Team'},{40},{'Blue'}},...
         {{'Receive Line 3 from Green Team'},{35},{'Blue'}},...
         {{'Balloon 3 Attached to Line 1'},{30},{'Blue'}},...
         {{'Launch Balloon 3'},{15},{'Blue'}},...
         {{'Receive Balloon 4 from Red Team'},{15},{'Blue'}},...
         {{'Receive Line 4 from Green Team'},{10},{'Blue'}},...
         {{'Balloon 4 Attached to Line 4'},{5},{'Blue'}},...
         {{'Launch Balloon 4'},{0},{'Blue'}}};
     
     
     
 while(1)
    clc
    minuteDuration = (1/24/60);
    forwardLook = 30;
    for i = 1:length(Tasks)
        taskTime = LaunchTime - Tasks{i}{2}{1}*minuteDuration;
        if taskTime > datetime && taskTime < datetime + forwardLook*minuteDuration
            cprintf(Tasks{i}{3}{1},'Team %s needs to complete %s in %.2f minutes\n',Tasks{i}{3}{1},Tasks{i}{1}{1},minutes(taskTime-datetime))
            j = j + 1;
        end
        
    end
    pause(1)
 end   
 
